# This workflow will do a clean installation of node dependencies, cache/restore
# them, build the source code and run tests across different versions of node
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run test on push or manually.

on:
  #[ push, workflow_dispatch ]:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Do we care about testing against different versions of node?
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at
        # https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # Is there a way to keep a cache of installed packages between different
    # versions of node to test with? This seems to be the slowest part of
    # our wf.
    # https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows
    - run: npm install
    - run: npm test
